// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzzqxhvnepgfuydfthrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6enF4aHZuZXBnZnV5ZGZ0aHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDM4MTUsImV4cCI6MjA3MzI3OTgxNX0.GbLwMTiPwINHHdvILJnR0tJO5pWZ_8t8wHfOfhxZqXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});