// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olfdejzgyxcdqkfyrvce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZmRlanpneXhjZHFrZnlydmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjI1MzcsImV4cCI6MjA3MjgzODUzN30.Jf6PDOPgfLVSPkSPi-egNqBqcw2K0R4suWmR46EErc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});